version: "3.8"

networks:
  coolnet:
   driver: bridge
   name: coolnet

services:
  nginx:
    restart: always
    container_name: nginx-proxy
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - './nginx_def_dev.conf:/etc/nginx/nginx.conf'
    depends_on:
      - gui
      - server
    networks:
      - coolnet
  gui:
    build:
      context: ./gui
    restart: always
    container_name: gui
    depends_on:
      - server
    networks:
      - coolnet
  server:
    build:
      context: ./server
    container_name: fast_api_server
    command: npm run start:dev
    ports:
      - 8000:8000
    restart: always
    env_file: "./server/.env"
    networks:
      - coolnet
